name: Auto-Deploy to S3

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - name: Checkout and prepare code
      uses: actions/checkout@v4
      
    - name: Terraform Apply
      run: |
        cd /home/vm1/s3_deoloy
        terraform init -reconfigure
        terraform apply -auto-approve
        
    - name: Sync to S3
      run: |
        cd /home/vm1/s3_deoloy
        export BUCKET_NAME=$(terraform output -raw todolist)
        aws s3 sync $GITHUB_WORKSPACE/ s3://$BUCKET_NAME \
          --exclude ".git/*" \
          --exclude ".github/*" \
          --delete
