name: Remote Terraform Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.VM1_SSH_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan ${{ secrets.VM1_HOST }} >> ~/.ssh/known_hosts
        
    - name: Test Connection
      run: ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no ${{ secrets.VM1_USER }}@${{ secrets.VM1_HOST }} "echo 'SSH connection successful!'"
      
    - name: Copy Files to VM1
      run: scp -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no -r . ${{ secrets.VM1_USER }}@${{ secrets.VM1_HOST }}:/tmp/website-code
      
    - name: Run Terraform on VM1
      run: |
        ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no ${{ secrets.VM1_USER }}@${{ secrets.VM1_HOST }} << 'EOF'
        cd /tmp/website-code
        terraform init
        terraform validate
        terraform plan
        if [ "$GITHUB_EVENT_NAME" = "push" ]; then
          terraform apply -auto-approve
        fi
        EOF
