name: Auto-Deploy to S3

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted  # Uses your VM1 runner
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Pull Site Files
      run: | 
        git clone https://github.com/Laiba-Azam/Todolist.git /tmp/site-files/
        cp -r /tmp/site-files/* .
    - name: Terraform Apply
      run: |
        cd /home/vm1/s3_deoloy
        terraform init -reconfigure
        terraform apply -auto-approve

    - name: Sync Site Files
      run: |
        cd /home/vm1/s3_deoloy
        export BUCKET_NAME=$(terraform output -raw todolist)
        aws s3 sync ../ s3://$BUCKET_NAME \
          --exclude ".git/*" \
          --exclude ".github/*" \
          --exclude "/home/vm1/s3_deoloy/*" \
          --delete
